### PR TITLE
Fix transformation functions

### LINKED ISSUE #47: Transformers have no effect
Calling `.transform(fn)` on a context currently has no effect.  The transformer is never called, and the S3 object is always converted to a string.

### PR DESCRIPTION
**Pull request by schmod**
Ensures that transformation functions and encoding settings are actually passed through to the underlying S3 service calls.  Previously, `context.transform()` and `context.encoding()` had absolutely no effect.

Adds some documentation to give slightly more detail about how transformation functions should be used, and correctly notes the structure of the objects that are passed into transformation functions.

Slightly restructures tests to use tape's built-in assertions.  (While writing my tests, I discovered that the existing array-equality assertions didn't actually do anything)

Also fixes an unrelated bug where calling `forEach()` would reset (and persist) the context's `concurrency` to `1`, and adds tests to ensure that `forEach` does not exhibit any parallelism.

Fixes #47

### CODE REVIEW

File: lib/Request.js [hunk 1]
```diff
@@ -155,10 +154,10 @@ class Request {
    * Promise).
    */
 
-  each(func, isAsync) {
+  each(func, isAsync, concurrency) {
```
Comment (wellsjo) [inline lib/Request.js]: the concurrency can be set for any function other than `forEach`, so this seems unnecessary to me. Why not stick with the original code for consistency?

Comment (wellsjo) [inline lib/Request.js]: actually I think I see what you're saying...forEach sets the concurrency to `1`, so chaining off the same context leaves the concurrency that way?

Comment (schmod) [inline lib/Request.js]: Yeah.  If you do something like

```
const ctx = context.concurrency(4);

ctx.forEach(someFn)
  .then(() => ctx.map(anotherFn))
```

the `.map()` would run with a concurrency of `1`, which doesn't quite seem like a reasonable or expected behavior.

Comment (wellsjo) [inline lib/Request.js]: totally. okay, this looks good! thank you!
